name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main     

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./apps/api

    steps:
      - name: Repo setup
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: "npm"   

      - name: Install dependencies
        run: npm install
        working-directory: .  

      - name: Run TypeScript Type Check
        run: npx tsc --noEmit

      - name: Run linter
        run: npm run lint

      - name: Build the code
        run: npm run build    